### ISSUE TITLE
latest supported/tested Java version

### ISSUE THREAD

**Issue by seriouslyEnter** [Naoghuman/lib-fxml#74]
I would like to read in the documentation if it works with Java 11.

I see in the requirements java 8 mentioned, but it is not specific enough.
Could you please mention which the latest Java version it works with or is tested with.
And maybe if Java 8 is minimum requirement or the latest supported version.

Thank you

**Comment by Naoghuman** [comment]
Hi @seriouslyEnter ,
thx for you question.

Currently Lib-FXML is fresh in development which is the reason that I am use the suffix '-PRERELEASE' in the release-name and also why the library isn't available in Maven Central. That is also the reason why the documentation is in the momentary state (will be extended with the next releases).

Momentary the library is only tested against 'Java 8'. Later I plan also a version for the later java versions. But momentary the development and stabilization from the api have priority.

Greeting
Naoghuman

**Comment by seriouslyEnter** [comment]
Thanks, I keep watching.
Can't wait to see what you do next for JavaFX.
Also I was a happy user of your netbeans plugin.

**Comment by Naoghuman** [comment]
I have also to thx for your positive feedback.
In the next two weeks the next version for Lib-FXML will be released with some exciting new features.
Hm with Lib-FXML I won't use afterburner.fx any more in the future, so I should also update (or write a new one) the plugin :) .
